function Hd = filter_lp_elliptic_order_10
%FILTER_LP_ELLIPTIC_ORDER_10 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.13 and Signal Processing Toolbox 9.1.
% Generated on: 11-Dec-2024 16:45:31

% Elliptic Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = 48000;  % Sampling Frequency

N     = 10;      % Order
Fpass = 9600;    % Passband Frequency
Apass = 1;       % Passband Ripple (dB)
Astop = 122.16;  % Stopband Attenuation (dB)

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.lowpass('N,Fp,Ap,Ast', N, Fpass, Apass, Astop, Fs);
Hd = design(h, 'ellip');

% [EOF]
