function Hd = filter_2_order_8
%FILTER_2_ORDER_8 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.13 and Signal Processing Toolbox 9.1.
% Generated on: 15-Dec-2024 18:05:35

% Elliptic Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in kHz.
Fs = 384;  % Sampling Frequency

Fpass = 20;      % Passband Frequency
Fstop = 48;      % Stopband Frequency
Apass = 1;       % Passband Ripple (dB)
Astop = 122.16;  % Stopband Attenuation (dB)
match = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
Hd = design(h, 'ellip', 'MatchExactly', match);

% [EOF]
