function Hd = filter_order_5687
%FILTER_ORDER_5687 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.13 and Signal Processing Toolbox 9.1.
% Generated on: 15-Dec-2024 12:42:41

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in kHz.
Fs = 6144;  % Sampling Frequency

Fpass = 20;                % Passband Frequency
Fstop = 24;                % Stopband Frequency
Dpass = 0.057501127785;    % Passband Ripple
Dstop = 7.7983011052e-07;  % Stopband Attenuation
dens  = 20;                % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
