function Hd = ellipticOrdre11
%ELLIPTICORDRE11 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.13 and Signal Processing Toolbox 9.1.
% Generated on: 16-Dec-2024 10:32:26

% Elliptic Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = 7056000;  % Sampling Frequency

Fpass = 20000;   % Passband Frequency
Fstop = 24000;   % Stopband Frequency
Apass = 1;       % Passband Ripple (dB)
Astop = 98;      % Stopband Attenuation (dB)
match = 'both';  % Band to match exactly

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
Hd = design(h, 'ellip', 'MatchExactly', match);

% [EOF]
