function Hd = ellipticOrdre7
%ELLIPTICORDRE7 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.13 and Signal Processing Toolbox 9.1.
% Generated on: 16-Dec-2024 10:47:01

% Elliptic Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are normalized to 1.

Fpass = 0.003;   % Passband Frequency
Fstop = 0.007;   % Stopband Frequency
Apass = 1;       % Passband Ripple (dB)
Astop = 98;      % Stopband Attenuation (dB)
match = 'both';  % Band to match exactly

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop);
Hd = design(h, 'ellip', 'MatchExactly', match);

% [EOF]
